### ISSUE TITLE
My Generate password click is not working, i have just done code till your "Forms" lecture, Please help

### ISSUE THREAD

**Issue by prateekj73** [zappycode/django3-password-generator#1]
My files
1. URL.py

from django.contrib import admin
from django.urls import path
from generator import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home ),
    path('generatedpassword/',views.password, name='password'),
]

views.py

from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request,'generator/home.html')

def password(request):
    return render(request,'generator/passwordpage.html')    

home.html --file attached

passwordpage.html

<html>
Here's your password
</html> 

@zappycode please help sir 
![url](https://user-images.githubusercontent.com/63036889/78254667-e250dc80-7513-11ea-8b6e-f91417ab3058.PNG)
![views](https://user-images.githubusercontent.com/63036889/78254673-e41aa000-7513-11ea-876e-dc9026e238c0.PNG)

![Capture](https://user-images.githubusercontent.com/63036889/78254434-89814400-7513-11ea-96e4-3e5eb950dba4.PNG)

**Comment by zappycode** [comment]
Hey there! Can you ask this in the course Q and A please? Thanks!
