### ISSUE TITLE
Capture the refresh Activity of Web Page to a Button

### ISSUE THREAD

**Issue by mishra-atul5001** [zappycode/django3-password-generator#3]
My Motive is to provide user a Button `Refresh Password` which would just generate again a new password in the password page and avoid hitting the REFRESH Button of the Web page.
I tried using POST method but didn't helped.
Any clue!?

**Comment by 3DCoded** [comment]
You could use JavaScript.
`<button onclick="window.reload();">Refresh Password</button>`

**Comment by zappycode** [comment]
Thanks for the idea @smattar2020! Going forward, let's not do questions as github issues @mishra-atul5001 :D
